
server:
  port: 8081

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"

      routes:
        - id: user-ws
          uri: lb://user-ws
          predicates:
            - Path=/api/v1.0/market/user/**

      discovery:
        enabled: true
        locator:
          enabled: true


  application:
    name: api-gateway

  boot:
    admin:
      client:
        url: "http://localhost:9090"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      - defaultZone: http://52.71.68.236:8761/eureka
  instance:
    hostname: localhost